
const subjectsData = {

  ME: {
    "1st - 1st": [
      "Communication Skills-I",
      "Applied Mathematics-I",
      "Applied Physics-I",
      "Applied Chemistry",
      "Engineering Drawing-I",
      "Basics of Information Technology",
      "General Workshop Practice-I",
    ],
    "1st - 2nd": [
      "Applied Mathematics-II",
      "Applied Physics-II",
      "Applied Mechanics",
      "General Engineering",
      "Engineering Drawing-II",
      "General Workshop Practice-II",
    ],
    "2nd - 3rd": [
      "Applied Mathematics-III",
      "Engineering Materials",
      "Mechanics of Solids",
      "Thermal Engineering",
      "Computer Aided Drafting and 3D Modelling",
      "Workshop Technology",
    ],
    "2nd - 4th": [
      "Communication Skills-II",
      "Refrigeration and Air Conditioning",
      "Hydraulics and Pneumatics",
      "Computer Aided Design and Manufacturing",
      "Environmental Studies & Disaster Management",
      "Energy Conservation",
      "Universal Human Values",
    ],
    "3rd - 5th": [
      "Industrial Training",
      "Industrial Management & Entrepreneurship Development",
      "Theory of Machines",
      "Machine Design",
      "Production Technology",
      "Production Management",
      "Automobile Engineering",
    ],
    "3rd - 6th": [
      "Industrial Engineering",
      "Metrology and Measuring Instruments",
      "CNC Machines and Automation",
      "Repair and Maintenance",
      "Tool Engineering",
    ],
  },

  EE: {
    "1st - 1st": [
      "Communication Skills-I",
      "Applied Mathematics-I",
      "Applied Physics-I",
      "Applied Chemistry",
      "Engineering Drawing-I",
      "Basics of Information Technology",
      "General Workshop Practice-I",
    ],
    "1st - 2nd": [
      "Applied Mathematics-II",
      "Applied Physics-II",
      "Basic Electrical Engineering",
      "Basics of Mechanical and Civil Engineering",
      "Analog Electronics",
      "General Workshop Practice-II",
    ],
    "2nd - 3rd": [
      "Applied Mathematics-III",
      "Electrical Instrumentation and Measurement",
      "Electrical and Electronics Engineering Materials",
      "Digital Electronics",
      "Electrical Machine-I",
      "Environmental Studies & Disaster Management",
    ],
    "2nd - 4th": [
      "Communication Skill-II",
      "Industrial Electronics and Control",
      "Electrical Design, Drawing and Estimating I",
      "Power Plant Engineering",
      "Transmission and Distribution of Electrical Power",
      "Energy Conservation",
      "Universal Human Values",
    ],
    "3rd - 5th": [
      "Industrial Management & Entrepreneurship Development",
      "Switchgear and Protection",
      "PLC, Microcontroller and SCADA",
      "Electrical Machine-II",
      "Renewable Sources of Energy",
      "Electric Traction",
      "Control of Electrical Machine",
      "Energy Management",
    ],
    "3rd - 6th": [
      "Installation, Maintenance and Repair of Electrical Equipment",
      "Electrical Design, Drawing and Estimating II",
      "Utilization of Electrical Energy",
      "Application of Computer Software in Electrical Engineering",
    ],
  },

  CSE: {
    "1st - 1st": [
      "Communication Skill-I",
      "Applied Mathematics-I",
      "Applied Physics-I",
      "Applied Chemistry",
      "Fundamentals of Computer and Information Technology",
      "Technical Drawing",
    ],
    "1st - 2nd": [
      "Applied Mathematics-II",
      "Applied Physics-II",
      "Basics of Electrical and Electronics Engineering",
      "Multimedia & Animation",
      "Concept of Programming Using C",
      "Office Automation Tools",
    ],
    "2nd - 3rd": [
      "Applied Mathematics-III",
      "Internet and Web Technology",
      "Environmental Studies & Disaster Management",
      "Data Communication and Computer Network",
      "Data Structure Using C",
      "Digital Electronics",
    ],
    "2nd - 4th": [
      "Communication Skill-II",
      "Database Management System",
      "Object Oriented Programming Using Java",
      "Operating Systems",
      "E-Commerce and Digital Marketing",
      "Energy Conservation",
      "Universal Human Values",
    ],
    "3rd - 5th": [
      "Software Engineering",
      "Web Development using PHP",
      "Computer Programming using Python",
      "Internet of Things",
      "Computer Architecture and Hardware Maintenance",
    ],
    "3rd - 6th": [
      "Development of Android Applications",
      "Cloud Computing",
      "Industrial Management & Entrepreneurship Development",
      "Advance Java",
      "DotNet Technologies",
      "Data Science and Machine Learning",
    ],
  },

  IT: {
    "1st - 1st": [
      "Communication Skill-I",
      "Applied Mathematics-I",
      "Applied Physics-I",
      "Applied Chemistry",
      "Fundamentals of Computer and Information Technology",
      "Technical Drawing",
    ],
    "1st - 2nd": [
      "Applied Mathematics-II",
      "Applied Physics-II",
      "Basics of Electrical and Electronics Engineering",
      "Multimedia & Animation",
      "Concept of Programming Using C",
      "Office Automation Tools",
    ],
    "2nd - 3rd": [
      "Applied Mathematics-III",
      "Internet and Web Technology",
      "Environmental Studies & Disaster Management",
      "Data Communication and Computer Network",
      "Data Structure Using C",
      "Computer Architecture and Hardware Maintenance",
    ],
    "2nd - 4th": [
      "Communication Skill-II",
      "Database Management System",
      "Object Oriented Programming Using Java",
      "Operating Systems",
      "E-Commerce and Digital Marketing",
      "Energy Conservation",
      "Universal Human Values",
    ],
    "3rd - 5th": [
      "Software Engineering",
      "Web Development using PHP",
      "Computer Programming using Python",
      "Internet of Things",
      "Information Security & IT Laws",
    ],
    "3rd - 6th": [
      "Development of Android Applications",
      "Cloud Computing",
      "Industrial Management & Entrepreneurship Development",
      "Advance Java",
      "Big Data",
      "Data Science and Machine Learning",
      "Digital Image Processing",
    ],
  },

  IC: {
    "1st - 1st": [
      "Communication Skills-I",
      "Applied Mathematics-I",
      "Applied Physics-I",
      "Applied Chemistry",
      "Engineering Drawing-I",
      "Engineering Mechanics and Materials",
      "Basics of Information Technology",
      "General Workshop Practice-I",
    ],
    "1st - 2nd": [
      "Applied Mathematics-II",
      "Applied Physics-II",
      "Electrical Engineering-1",
      "Basic Electrical Engineering",
      "Electronic Components and Devices",
      "Basics of Information Technology",
      "Analog Electronics",
      "General Workshop Practice-II",
    ],
    "2nd - 3rd": [
      "Applied Mathematics-III",
      "Electrical Engineering-II",
      "Electrical Instrumentation and Measurement",
      "Environmental Studies & Disaster Management",
      "Electronic Devices and Circuits",
      "Digital Electronics",
      "Electronics Workshop",
      "Transducer and Application",
      "Universal Human Values",
    ],
    "2nd - 4th": [
      "Communication Skill-II",
      "Principles of Digital Electronics",
      "Network Filters and Transmission Lines",
      "Electronic Instruments and Measurement",
      "Process Instrumentation",
      "Power Plant Engineering",
      "Energy Conservation",
    ],
    "3rd - 5th": [
      "Industrial Management & Entrepreneurship Development",
      "Microprocessor & Peripheral Devices",
      "Industrial Control",
      "Signal Transmission Recording and Display",
      "Programming in C",
    ],
    "3rd - 6th": [
      "Process Control",
      "Microcontrollers and Embedded System",
      "Bio-Medical Instrumentation",
      "Specialised Instruments",
      "Robotics",
      "Neural Networks",
    ],
  },

  MOM: {
    "1st - 1st": [
      "Communication Skills-I",
      "Modern Office Management",
      "Computer Typing Theory",
      "Shorthand Hindi I",
      "Shorthand English I",
      "Computer Typing Hindi I",
      "Computer Typing English I",
    ],
    "1st - 2nd": [
      "Elementary Book-keeping & Accountancy",
      "Universal Human Values",
      "Shorthand Hindi Theory",
      "Shorthand English Theory",
      "Shorthand Hindi II",
      "Shorthand English II",
      "Computer Typing Hindi II",
      "Computer Typing English II",
      "Course on Computer Concept",
    ],
    "2nd - 3rd": [
      "Office & Business Correspondence in English",
      "Communication Skills II",
      "Shorthand Hindi III",
      "Shorthand English III",
      "Computer Typing Hindi III",
      "Computer Typing English III",
      "Computer Accountancy",
      "E-Commerce and Secretarial Practice",
    ],
    "2nd - 4th": [
      "Industrial Management & Entrepreneurship Development",
      "Vocational Hindi and Correspondence",
      "Personality Development",
      "Environmental Studies & Disaster Management",
      "Shorthand Hindi IV",
      "Shorthand English IV",
      "Computer Typing Hindi IV",
      "Computer Typing English IV",
      "Field Exposure",
    ],
    "3rd - 5th": [],
    "3rd - 6th": [],
  },

  PGDCA: {
    "1st - 1st": [
      "Basics of Computer and Information Technology",
      "Computer Programming Using Python",
      "Data Communication and Computer Network",
      "Office Automation Tools",
      "Internet and Web Technology",
    ],
    "1st - 2nd": [
      "Operating System",
      "Web Designing Tools",
      "Data Structure Using Python",
      "Software Engineering",
      "Database Management System",
    ],
    "2nd - 3rd": [],
    "2nd - 4th": [],
    "3rd - 5th": [],
    "3rd - 6th": [],
  },
};
