
const teachersData = {

    ME: [
        "Mr. P.C. Katiyar",
        "Mr. Ravindera Solanki",
        "Mr. Avneesh Verma",
        "Mr. Ashish Kumar",
        "Mr. Ratnesh Sonkar",
        "Mr. Ram Chandra Verma",
        "Dr. Anjali Trivedi",
    ],

    EE: [
        "Dr. Nisheeth Upadhyay",
        "Ms. Shweta Verma",
        "Dr. Anjali Trivedi",
        "Mr. Mridul Pandey",
        "Sandeep Singh",
        "Ms. Saumya Mishra",
        "Mr. Ganesh Mishra",
        "Mr. Anoop Shukla",
        "Mr. Virendra Yadav",
    ],

    CSE: [
        "Mr. S.K. Kannaujia",
        "Dr. Nitya Bajpai",
        "Ms. Sarita Srivastava",
        "Mr. Ishrat Hussain",
        "Ms. Apoorva Singh",
        "Ms. Shweta Srivastava",
        "Ms. Sonal Verma",
        "Ms. Kiran Yadav",
        "Ms. Deepanjali Singh",
        "Ms. Faqeha Siddiqui",
        "Ms. Sandhya Dwivedi",
        "Mr. Ashish Kumar",
        "Mr. Jitendra Kumar",
        "Ms. Sushma Sahu",
        "Mr. Deep Kumar Soni",
    ],

    IT: [
        "Mr. S.K. Kannaujia",
        "Dr. Nitya Bajpai",
        "Ms. Sarita Srivastava",
        "Mr. Ishrat Hussain",
        "Ms. Apoorva Singh",
        "Ms. Shweta Srivastava",
        "Ms. Sonal Verma",
        "Ms. Kiran Yadav",
        "Ms. Deepanjali Singh",
        "Ms. Faqeha Siddiqui",
        "Ms. Sandhya Dwivedi",
        "Mr. Ashish Kumar",
        "Mr. Jitendra Kumar",
        "Ms. Sushma Sahu",
        "Mr. Deep Kumar Soni",
    ],

    IC: [
        "Ms. Renu Gautam",
        "Dr. Mridul Pandey",
        "Mr. Sandeep Kumar",
        "Mr. Mannu Kumar",
        "Mr. Anoop",
        "Mr. Zaid Ansari",
        "Ganesh Mishra",
    ],

    MOM: ["Mr. C.S. Saroj"],

    PGDCA: [
        "Mr. S.K. Kannaujia",
        "Dr. Nitya Bajpai",
        "Ms. Sarita Srivastava",
        "Mr. Ishrat Hussain",
        "Ms. Apoorva Singh",
        "Ms. Shweta Srivastava",
        "Ms. Sonal Verma",
        "Ms. Kiran Yadav",
        "Ms. Deepanjali Singh",
        "Ms. Faqeha Siddiqui",
        "Ms. Sandhya Dwivedi",
        "Mr. Ashish Kumar",
        "Mr. Jitendra Kumar",
        "Ms. Sushma Sahu",
        "Mr. Deep Kumar Soni",
    ],
};
