const teachersData = {
    ME: [
        "Mr. P.C. Katiyar",
        "Mr. Sarvesh Kannaujia",
        "Mr. Ravindra Solanki",
        "Mr. Avneesh Verma",
        "Mr. Ashish Kumar",
"Mr. Ashish Sonkar",
        "Mr. Ratnesh Sonkar",
        "Mr. Ram Chandra Verma",
        "Dr. Anjali Trivedi",
        "Mr. Mridul Pandey",
        "Mr. Shubham Sahu",
    ],

    EE: [
        "Dr. Nisheeth Upadhyay",
        "Ms. Shweta Verma",
        "Dr. Anjali Trivedi",
"Mr. Ashish Sonkar",
        "Mr. Mridul Pandey",
        "Mr. Sandeep Singh",
        "Ms. Saumya Mishra",
        "Mr. Ganesh Mishra",
        "Mr. Anoop Shukla",
        "Mr. Virendra Yadav",
        "Mr. Shubham Sahu",
    ],

    CSE: [
        "Mr. S.K. Kannaujia",
        "Dr. Nitya Bajpai",
        "Ms. Sarita Srivastava",
        "Mr. Ishrat Hussain",
        "Ms. Apurva Singh",
        "Ms. Shweta Srivastava",
        "Ms. Sonal Verma",
        "Ms. Kiran Yadav",
        "Ms. Deepanjali Singh",
        "Ms. Faqeha Siddiqui",
        "Ms. Sandhya Dwivedi",
        "Mr. Ashish Sonkar",
        "Mr. Jitendra Kumar",
        "Ms. Sushma Sahu",
        "Mr. Deep Kumar Soni",
    ],

    IT: [
        "Mr. S.K. Kannaujia",
        "Dr. Nitya Bajpai",
        "Ms. Sarita Srivastava",
        "Mr. Ishrat Hussain",
        "Ms. Apurva Singh",
        "Ms. Shweta Srivastava",
        "Ms. Sonal Verma",
        "Ms. Sonal",
        "Ms. Kiran Yadav",
        "Ms. Deepanjali Singh",
        "Ms. Faqeha Siddiqui",
        "Ms. Sandhya Dwivedi",
        "Mr. Ashish Sonkar",
        "Mr. Jitendra Kumar",
        "Ms. Sushma Sahu",
        "Mr. Deep Kumar Soni",
    ],

    IC: [
        "Ms. Renu Gautam",
        "Dr. Mridul Pandey",
        "Mr. Sandeep Kumar",
        "Mr. Mannu Kumar",
"Mr. Ashish Sonkar",
        "Mr. Anoop",
        "Mr. Zaid Ansari",
        "Mr. Ganesh Mishra",
    ],

    MOM: ["Mr. C.S. Saroj"],

    PGDCA: [
        "Mr. S.K. Kannaujia",
        "Dr. Nitya Bajpai",
        "Ms. Sarita Srivastava",
        "Mr. Ishrat Hussain",
        "Ms. Apoorva Singh",
        "Ms. Shweta Srivastava",
        "Ms. Sonal Verma",
        "Ms. Kiran Yadav",
        "Ms. Deepanjali Singh",
        "Ms. Faqeha Siddiqui",
        "Ms. Sandhya Dwivedi",
        "Mr. Ashish Kumar",
        "Mr. Jitendra Kumar",
        "Ms. Sushma Sahu",
        "Mr. Deep Kumar Soni",
    ],
};
