
const teachersData = {
    ME: [
      "Mr. P.C. Katiyar Sir",
      "Mr. P.C. Katiyar",
      "Mr. Sarvesh Kannaujia Sir",
      "Mr. Sarvesh Kannaujia",
      "Mr. Ravindra Solanki Sir",
      "Mr. Ravindra Solanki",
      "Mr. Avneesh Verma Sir",
      "Mr. Avneesh Verma",
      "Mr. Ashish Kumar Sir",
      "Mr. Ashish Kumar",
      "Mr. Ratnesh Sonkar Sir",
      "Mr. Ratnesh Sonkar",
      "Mr. Ram Chandra Verma Sir",
      "Mr. Ram Chandra Verma",
      "Dr. Anjali Trivedi Ma'am",
      "Dr. Anjali Trivedi",
      "Mr. Mridul Pandey Sir",
      "Mr. Mridul Pandey",
      "Mr. Shubham Sahu Sir",
      "Mr. Shubham Sahu",
    ],
  
    EE: [
      "Dr. Nisheeth Upadhyay Sir",
      "Dr. Nisheeth Upadhyay",
      "Ms. Shweta Verma Ma'am",
      "Ms. Shweta Verma",
      "Dr. Anjali Trivedi Ma'am",
      "Dr. Anjali Trivedi",
      "Mr. Mridul Pandey Sir",
      "Mr. Mridul Pandey",
      "Mr. Sandeep Singh Sir",
      "Mr. Sandeep Singh",
      "Ms. Saumya Mishra Ma'am",
      "Ms. Saumya Mishra",
      "Mr. Ganesh Mishra Sir",
      "Mr. Ganesh Mishra",
      "Mr. Anoop Shukla Sir",
      "Mr. Anoop Shukla",
      "Mr. Virendra Yadav Sir",
      "Mr. Virendra Yadav",
      "Mr. Shubham Sahu Sir",
      "Mr. Shubham Sahu",
    ],
  
    CSE: [
      "Mr. S.K. Kannaujia Sir",
      "Mr. S.K. Kannaujia",
      "Dr. Nitya Bajpai Ma'am",
      "Dr. Nitya Bajpai",
      "Ms. Sarita Srivastava Ma'am",
      "Ms. Sarita Srivastava",
      "Mr. Ishrat Hussain Sir",
      "Mr. Ishrat Hussain",
      "Ms. Apoorva Singh Ma'am",
      "Ms. Apoorva Singh",
      "Ms. Shweta Srivastava Ma'am",
      "Ms. Shweta Srivastava",
      "Ms. Sonal Verma Ma'am",
      "Ms. Sonal Verma",
      "Ms. Sonal Verma Ma'am",
      "Ms. Sonal Verma",
      "Ms. Sonal Ma'am",
      "Ms. Sonal",
      "Ms. Kiran Yadav Ma'am",
      "Ms. Kiran Yadav",
      "Ms. Deepanjali Singh Ma'am",
      "Ms. Deepanjali Singh",
      "Ms. Faqeha Siddiqui Ma'am",
      "Ms. Faqeha Siddiqui",
      "Ms. Sandhya Dwivedi Ma'am",
      "Ms. Sandhya Dwivedi",
      "Mr. Ashish Kumar Sir",
      "Mr. Ashish Kumar",
      "Mr. Jitendra Kumar Sir",
      "Mr. Jitendra Kumar",
      "Ms. Sushma Sahu Ma'am",
      "Ms. Sushma Sahu",
      "Mr. Deep Kumar Soni Sir",
      "Mr. Deep Kumar Soni",
    ],
  
    IT: [
      "Mr. S.K. Kannaujia Sir",
      "Mr. S.K. Kannaujia",
      "Dr. Nitya Bajpai Ma'am",
      "Dr. Nitya Bajpai",
      "Ms. Sarita Srivastava Ma'am",
      "Ms. Sarita Srivastava",
      "Mr. Ishrat Hussain Sir",
      "Mr. Ishrat Hussain",
      "Ms. Apoorva Singh Ma'am",
      "Ms. Apoorva Singh",
      "Ms. Shweta Srivastava Ma'am",
      "Ms. Shweta Srivastava",
      "Ms. Sonal Verma Ma'am",
      "Ms. Sonal Verma",
      "Ms. Sonal Verma Ma'am",
      "Ms. Sonal Verma",
      "Ms. Sonal Ma'am",
      "Ms. Sonal",
      "Ms. Kiran Yadav Ma'am",
      "Ms. Kiran Yadav",
      "Ms. Deepanjali Singh Ma'am",
      "Ms. Deepanjali Singh",
      "Ms. Faqeha Siddiqui Ma'am",
      "Ms. Faqeha Siddiqui",
      "Ms. Sandhya Dwivedi Ma'am",
      "Ms. Sandhya Dwivedi",
      "Mr. Ashish Kumar Sir",
      "Mr. Ashish Kumar",
      "Mr. Jitendra Kumar Sir",
      "Mr. Jitendra Kumar",
      "Ms. Sushma Sahu Ma'am",
      "Ms. Sushma Sahu",
      "Mr. Deep Kumar Soni Sir",
      "Mr. Deep Kumar Soni",
    ],
  
    IC: [
      "Ms. Renu Gautam Ma'am",
      "Ms. Renu Gautam",
      "Dr. Mridul Pandey Sir",
      "Dr. Mridul Pandey",
      "Mr. Sandeep Kumar Sir",
      "Mr. Sandeep Kumar",
      "Mr. Mannu Kumar Sir",
      "Mr. Mannu Kumar",
      "Mr. Anoop Sir",
      "Mr. Anoop",
      "Mr. Zaid Ansari Sir",
      "Mr. Zaid Ansari",
      "Mr. Ganesh Mishra Sir",
      "Mr. Ganesh Mishra",
    ],
  
    MOM: ["Mr. C.S. Saroj Sir", "Mr. C.S. Saroj"],
  
    PGDCA: [
      "Mr. S.K. Kannaujia Sir",
      "Mr. S.K. Kannaujia",
      "Dr. Nitya Bajpai Ma'am",
      "Dr. Nitya Bajpai",
      "Ms. Sarita Srivastava Ma'am",
      "Ms. Sarita Srivastava",
      "Mr. Ishrat Hussain Sir",
      "Mr. Ishrat Hussain",
      "Ms. Apoorva Singh Ma'am",
      "Ms. Apoorva Singh",
      "Ms. Shweta Srivastava Ma'am",
      "Ms. Shweta Srivastava",
      "Ms. Sonal Verma Ma'am",
      "Ms. Sonal Verma",
      "Ms. Kiran Yadav Ma'am",
      "Ms. Kiran Yadav",
      "Ms. Deepanjali Singh Ma'am",
      "Ms. Deepanjali Singh",
      "Ms. Faqeha Siddiqui Ma'am",
      "Ms. Faqeha Siddiqui",
      "Ms. Sandhya Dwivedi Ma'am",
      "Ms. Sandhya Dwivedi",
      "Mr. Ashish Kumar Sir",
      "Mr. Ashish Kumar",
      "Mr. Jitendra Kumar Sir",
      "Mr. Jitendra Kumar",
      "Ms. Sushma Sahu Ma'am",
      "Ms. Sushma Sahu",
      "Mr. Deep Kumar Soni Sir",
      "Mr. Deep Kumar Soni",
    ],
  };
  
